INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACETA-01','Acetazolamid 250mg (Diamox)',1,1,16,NULL,NULL,2);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACETY-01','Acetylcysteine sandoz 600mg (ACC600)',1,1,16,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACETY-02','Acetylsalicylic acid 32mg (Apernyl )',1,11,18,NULL,'analgesia: treat mild to moderate pain after pulling a tooth',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACTAP-01','Actapulgite 1g sach/20',1,1,9,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACTAP-02','Actapulgite 3g sach/30',1,1,9,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACTIM-01','Actimo gel (etching gel)',1,4,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACTIV-01','Active Charcoal 500mg',1,1,16,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACUPA-01','Acupan  20mg/2ml(Nefopam)',1,2,11,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACYCL-01','Acyclovir 400mg',1,1,16,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ACYCL-02','Acyclovir 5% - 7g',1,11,7,NULL,'Antiviral cream',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ADREN-01','Adrenalin (epinephrin) 1mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ADREN-02','Adrenaline (epinephrine) 1 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ALBEN-01','Albendazole 200mg',1,1,4,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ALBEN-02','Albendazole 400mg',1,1,16,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ALBUT-01','Albuterol sulfate inhalation solution 0,083%',1,NULL,14,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ALDAC-01','Aldactone 50mg',1,1,16,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ALDAC-02','Aldactone 75mg',1,1,16,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ALLER-01','Allergika 1ml',1,11,7,NULL,'Sensitive Face Cream',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ALUMI-01','Aluminium Oxyd (maalox)',1,1,4,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ALVEO-01','Alveogyl 10',1,11,18,NULL,'local treatment of dry socket and as post-extraction dressing',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMALG-01','Amalgam',1,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMINO-01','Aminophyllin 100mg',1,1,16,NULL,'bronchodilator',1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMIOD-01','Amiodaron-ratiopharm 150mg/3ml',1,2,11,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMLOD-01','Amlodipin  5 mg',1,1,16,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMLOD-02','Amlodipin 10 mg',1,1,16,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMMON-01','Ammonia inhalents',1,9,6,NULL,NULL,1);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMOXI-01','Amoxicilin 500mg /5ml-100ml',1,1,9,NULL,NULL,2);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMOXI-02','Amoxicillin  250 mg/5ml-sp',1,1,9,NULL,NULL,2);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMOXI-03','Amoxicillin 1000 mg + clavulanic acid 200 mg (Fleming 1200 mg)',1,2,11,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMOXI-04','Amoxicillin 250mg',1,1,10,NULL,NULL,2);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMOXI-05','Amoxicillin 500mg',1,1,10,NULL,NULL,2);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMOXI-06','Amoxiclanic/500mg+62.5mg',1,1,10,NULL,NULL,2);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMOXI-07','Amoxiclav 1000mg',1,1,16,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMOXI-08','Amoxiclav beniclav  625mg',1,1,10,NULL,NULL,2);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMPHO-01','Amphotericin B Ampho-moronal 10mg',1,1,16,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMPIC-01','Ampicillin 1g-ppi',1,2,11,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AMPIC-02','Ampicillin 500mg-ppi (expired)',1,2,11,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ANEST-01','Anesthesia Syringes',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('APRES-01','Apresoline (Hydralazine hydrochloride) 20mg',1,2,11,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('APROV-01','Aprovel 300 mg',1,1,16,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AQUA -01','Aqua 10ml (eau pour prep. Inj)',1,2,11,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AQUA -02','Aqua 5ml (eau pour prep inj)',1,2,11,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AQUA -03','Aqua 60ml (eau pour prep. Inj)',1,2,11,NULL,NULL,3);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ARGIN-01','Arginin + complex vitamin (argi+) 10g',1,1,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ARTES-01','Artesunate Amodiaquine 100mg/270mg (ASAQ)',1,1,16,NULL,'Antimalarial',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ARTES-02','Artesunate Amodiaquine 25mg/67,5mg (ASAQ)',1,1,16,NULL,'Antimalarial',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ARTES-03','Artesunate Amodiaquine 50mg/135mg (ASAQ)',1,1,16,NULL,'Antimalarial',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ASPEG-01','aspegic adulte -aspirine 1g sach/20',1,1,9,NULL,'non-steroidal anti-inflammatory drug',4);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ASPEG-02','aspegic ---aspirine enfant newborn 100mg sach/20',1,1,9,NULL,'pediatric non-steroidal anti-inflammatory drug',4);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ASPIR-01','Aspirine 500mg',1,1,16,NULL,NULL,4);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ATENO-01','Atenolol 50mg (novaten)',1,1,16,NULL,'hypertension and angina and in stable heart attack medecine',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ATOVA-01','Atovaquo/Proguanil HCI 250/100mg',1,1,16,NULL,NULL,4);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ATOVA-02','Atovaquon hydrochlorid (Malarone) 250mg/100mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ATROP-01','Atropine Sulfate 0.25 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ATROP-02','Atropine Sulfate 0.5 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ATROP-03','Atropine Sulfate 1 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AZYTH-01','Azythromicin 250mg',1,1,16,NULL,NULL,4);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('AZYTH-02','Azythromicin 500mg',1,1,16,NULL,NULL,4);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BACIL-01','Bacilor Diarhee 1,5g',1,1,9,NULL,NULL,5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BARBE-01','Barbed broaches (dental)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BAYOT-01','Bayotensin  5mg/1ml',1,11,7,NULL,NULL,5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BEIDE-01','Beidellitic Montmorillonite 3g (bedelix)',1,1,9,NULL,NULL,5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BEPAN-01','Bepanthen  Augentropfen 20*0,5ml',1,7,4,NULL,NULL,5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BEPAN-02','Bepanthen 3,5g',1,11,7,NULL,'Antiseptic Cream',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BEROT-01','Berotec 100ug-10ml',1,9,20,NULL,NULL,5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BETAM-01','Betamethasone Valerate 100g',1,11,7,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BETAM-02','Betamethasone Valerate 15g',1,11,7,NULL,NULL,9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BISOP-01','Bisoprolol 10mg',1,1,16,NULL,'beta blocker medication most commonly used for heart diseases',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BISOP-02','Bisoprolol 2,5mg',1,1,16,NULL,'beta blocker medication most commonly used for heart diseases',5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BISOP-03','Bisoprolol 5mg',1,1,16,NULL,'beta blocker medication most commonly used for heart diseases',5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BRONC-01','Bronchicum 24mg',1,1,4,NULL,NULL,5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BRONC-02','Bronchospasmin 1ml',1,2,11,NULL,NULL,5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BRUSH-01','Brushes viva (dental)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BUDES-01','Budesonid 1mg/2ml',1,9,20,NULL,'Corticosteroid: long-term management of asthma and chronic obstructive pulmonary disease.',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BUPIV-01','Bupivacaine 0.25%, 12.5 mg/5 ml (Actavis)',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BUPIV-02','Bupivacaine 0.5%',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BUPIV-03','Bupivacaine 5 mg/4 ml (B-Cane Heavy)',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BUSCO-01','Buscopan Plus 10 mg',1,1,16,NULL,NULL,5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('BUTYL-01','BUTYLSCOPOLAMINE 20mg inj B/50 Amp 1ML(buscopon)',1,2,11,NULL,NULL,5);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CAFED-01','Cafedrin hydrochlorid 200 mg/2 ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CAFED-02','Cafedrin hydrochlorid 200mg/2ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CALCI-01','Calcium Citrate 1,56g/2,5g (kalinor)',1,1,16,NULL,'food additive (E333)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CALCI-02','Calcium fort 500mg',1,1,16,NULL,NULL,7);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CALCI-03','Calcium gluconate  10%/10ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CALCI-04','Calcium Hydroxyd 10% 10ml',1,4,9,NULL,'antibacterial / intracanal medicament',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CALCI-05','Calcium lactate 300mg (food complements)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CANDE-01','Candesartan 16mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CANEP-01','Canephron uno 36mg',1,1,16,NULL,'phytotherapeutic drug used for the supportive treatment and to supplement specific measures in case of mild complaints relating to inflammatory diseases of the efferent urinary tract; to flush out the urinary tract in order to prevent the deposition of renal sand.',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CAPTO-01','Captopril 25mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CARBA-01','Carbamazepine 200mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CARBI-01','Carbimazole 10mg',1,1,16,NULL,'is an anti-thyroid agent',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CARBO-01','Carbocistein 100mg- 100ml-2%',1,1,4,NULL,'Adult mucolytic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CARBO-02','Carbocistein 250mg- 100ml-5%',1,1,4,NULL,'Pediatric mucolytic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CAVIF-01','Cavifil  (tetric ovoflow) A2',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CAVIF-02','Cavifil  (tetric ovoflow) A3,5',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CEFAL-01','Cefalexin 30ml',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CEFAZ-01','Cefazolin 2g (EXP 2018)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CEFIX-01','Cefixime (oroken) 100mg/ml',1,1,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CEFTR-01','Ceftriaxone 1g 10ml/g',1,2,11,NULL,'antibiotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CEFTR-02','Ceftriaxone 2g',1,2,11,NULL,'antibiotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CEFUR-01','Cefuroximaxetil 250mg',1,1,16,NULL,'antibiotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CEFUR-02','Cefuroximaxetil 500mg',1,1,16,NULL,'antibiotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CELES-01','Celesten 30ml',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CEPHA-01','Cephadex 30ml',1,1,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CERVI-01','cervidil 1mg',1,6,12,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CETIR-01','Cetirizin hydrochlorid 10mg',1,1,16,NULL,'antihistaminic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CETRI-01','Cetrimid 15g',1,11,7,NULL,'antiseptic',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CETRI-02','Cetrimid 30g',1,11,7,NULL,'antiseptic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHARM-01','Charm bond',1,4,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHLOR-01','Chlorethan (active ice spray) -100ml',1,11,19,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHLOR-02','Chlorethan 100 ml (Active Ice Spray)',1,11,19,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHLOR-03','Chlorexydin 5ml',1,NULL,14,NULL,'antiseptic antibacterial agents',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHLOR-04','Chlorobutanol 30ml',1,11,18,NULL,'antibacterial and antifungal local anesthetic',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHLOR-05','Chlorpheniramin 100ml (pulmokoff)',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHLOR-06','Chlorpheniramin 60ml (cheston)',1,1,4,NULL,'antihistaminic-decongestant-mild analgesic and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHLOR-07','Chlorpheniramin sp 100ml',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHLOR-08','Chlorpheniramine 4mg',1,1,16,NULL,'antihistaminic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CHLOR-09','Chlortetracyclin Hydrochloride (Aureomycin) 10mg/g',1,11,7,NULL,'Antibiotic',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CIMET-01','Cimetidine 200mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CIPRO-01','Ciprofloxacin 200mg/100ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CIPRO-02','Ciprofloxacin 250mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CIPRO-03','Ciprofloxacin 500mg',1,1,16,NULL,'Antibiotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CITRA-01','Citrate de cafeine 25mg/ml-2ml',1,13,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CLEXA-01','Clexane 40mg/0,4ml-4000ie',1,12,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CLEXA-02','Clexane 60mg/0,6ml-6000ie',1,12,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CLIND-01','Clindamycin 150mg/ml-600mg/4ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CLIND-02','Clindamycin 300mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CLIND-03','Clindamycin 600mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CLOTR-01','Clotrimazole 1% 20g',1,11,7,NULL,'Antifungal',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CLOTR-02','Clotrimazole 1% 30g',1,11,7,NULL,'Antifungal',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CLOXA-01','Cloxacyllin 250mg',1,1,10,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('COLCH-01','Colchicin 1mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('COLEC-01','Colecalciferol 1000ie',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('COLEC-02','Colecalciferol 2000ie',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('COLEC-03','Colecalciferol 500ie (D-fluoretten)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CONDO-01','Condom female',2,NULL,14,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CONTR-01','Contramutan 100ml',1,1,4,NULL,'anti-inflammatory and antiviral :homeopatic syrup for kids against cold',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('COROR-01','cororange 15ml',1,1,9,NULL,'iron+multivit',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('COTRI-01','Cotrimoxazole 240mg/5ml',1,1,4,NULL,'antibiotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('COTRI-02','Cotrimoxazole 480mg',1,1,16,NULL,'antibiotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('COTRI-03','Cotrimoxazole 960-160mg/800mg',1,1,16,NULL,'antibiotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('CUTAC-01','Cutacnyl 5% -gel derm tbe 40g',1,11,7,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DACUD-01','Dacudoses 10ml',1,7,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DESLO-01','Desloratadine 0,5mg/ml-60ml (Aerius)',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DESMO-01','desmopressin acetate 10ug-5ml (Minirin)',1,8,19,NULL,'vasopressin',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DETAR-01','Detartrine 45g',1,11,18,NULL,'Dental polisher and filling',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DEXAM-01','Dexamethasone 4mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DEXAM-02','Dexamethasone 4mg/1ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DEXAM-03','Dexamethasone 8mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DIAZE-01','Diazepam 10 mg/2 ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DIAZE-02','Diazepam 10 mg/ml - 25ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DIAZE-03','Diazepam 10mg/ml-20ml',1,13,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DIAZE-04','Diazepam 5mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DICLO-01','Diclo retard 100mg',1,1,16,NULL,'analgesic and anti-inflammatory drugs (NSAIDs)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DICLO-02','Diclofenac 25mg',1,1,16,NULL,'analgesic and anti-inflammatory drugs (NSAIDs)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DICLO-03','Diclofenac 25mg/ml-3ml',1,2,11,NULL,'analgesic and anti-inflammatory drugs (NSAIDs)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DICLO-04','Diclofenac 50mg',1,1,16,NULL,'analgesic and anti-inflammatory drugs (NSAIDs)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DICLO-05','Diclofenac 75mg',1,1,16,NULL,'analgesic and anti-inflammatory drugs (NSAIDs)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DICLO-06','Diclofenac 75mg/2ml',1,2,11,NULL,'analgesic and anti-inflammatory drugs (NSAIDs)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DICLO-07','Diclofenac Gel 20g',1,11,7,NULL,NULL,9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DICLO-08','Diclofenac retard 75mg SL',1,1,10,NULL,'analgesic and anti-inflammatory drugs (NSAIDs)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DICLO-09','Diclofenac sodium 100mg',1,5,21,NULL,'analgesic and anti-inflammatory drugs (NSAIDs)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DIGES-01','Digestive water (Pinkoo)120ml',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DIMEN-01','Dimenhydrinat 70mg (vomacur)',1,5,21,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DIMET-01','Dimetinden maleat 1% (Fenistil)',1,11,7,NULL,'Anti-allergic Cream',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DIMET-02','Dimetindene- 1mg/ml-4ml(antihistamine/anticholinergic)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DIOSM-01','Diosmectite 3g',1,1,9,NULL,'pediatric antidiarhea',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DOMPE-01','Domperidone 1mg/ml-30ml',1,1,4,NULL,'anti-sickness Domperidone is sometimes used to increase milk supply.',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DOXYC-01','Doxycyclin  100mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DOXYC-02','Doxycyclin  200mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DOXYC-03','Doxycyclin 100mg/5ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DOXYC-04','Doxycyclin 50mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DRILL-01','Drill dental balls (fraise a boule)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DRILL-02','Drill dental HP12/i50031 (fraise)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DROTA-01','Drotaverin (no-spa) 40mg/2ml',1,2,11,NULL,'treatment of smooth muscle contractions (felt as recurrent stomach pain) in the gastrointestinal tract, gall bladder and urinary tract.',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DROTA-02','Drotaverin hydrochlorid 40mg',1,1,16,NULL,'treatment of smooth muscle contractions (felt as recurrent stomach pain) in the gastrointestinal tract, gall bladder and urinary tract.',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DUAL--01','Dual-Cure Resin Cements',1,NULL,14,NULL,'polymerization activator',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('DUPHA-01','Duphalac lactulose 10g/15ml-',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ENALA-01','Enalapril (captopril) 5mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('EPHED-01','Ephedrine 30 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ERGOC-01','Ergocalciferol 2,000,000ui/100ml (sterogyl)',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ERYTH-01','Erythromycine 100ml',1,1,9,NULL,'antibiotic treating infections of the respiratory tract, including bronchitis, pneumonia, diphtheria',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ERYTH-02','Erythromycine 1g',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ERYTH-03','Erythromycine 250mg',1,1,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ERYTH-04','Erythromycine 500mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ETILE-01','Etilefrin hydrochloride 7.5 mg/ml (Effortil) 30ml',1,13,9,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ETYLE-01','Etylephrin hydrochlorid 7,5mg/ml (effortyl)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('EUGEN-01','Eugenol 100ml',1,11,4,NULL,'herbal oil used topically to treat toothache',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('EUPHR-01','Euphrasia 0,5ml',1,7,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FENTA-01','Fentanyl 0.5 mg/ml (Rapifen)',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FENTA-02','Fentanyl 100 mcg/2 ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FENTA-03','Fentanyl Hydrochlorid 10ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FENTA-04','Fentanyl Hydrochlorid 2ml -100ug',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FERRO-01','Ferrous sulfate glycin (iron complex) 30mg/ml',1,1,9,NULL,'oral iron preparation for iron deficiency',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FERRO-02','Ferrous Sulphate 200mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FLUCL-01','Flucloxacillin 500mg (staphylex)',1,1,10,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FLUCO-01','Fluconazole 100mg',1,1,10,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FLUIN-01','Fluindione (Previscan)20mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FLUMA-01','Flumazenil 0.1 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FLUTI-01','Fluticasone Propionate (120dosages)',1,8,19,NULL,'steroid medication',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FOLIC-01','Folic Acid +VitC+Ferrous sulphate',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FOLIC-02','Folic Acid 0,4mg + Ferrous sulfate 200mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FOLIC-03','Folic Acid 5mg',1,1,16,NULL,'dietary supplement and in food fortification (during pregnancy)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FRAME-01','Framecytin sulfate+dexamethasone (Frakidex) 100mg',1,7,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FUCID-01','Fucidin 20mg/g',1,11,7,NULL,'antibiotic used in the treatment of bacterial skin infections such as impetigo and infected dermatitis.',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FUROS-01','Furosemide (lazilix) 20mg/2ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FUROS-02','Furosemide (lazilix) 40mg',1,1,16,NULL,'diuretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('FUROS-03','Furosemide (lazilix) 500mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('GAUZE-01','Gauze 6x6xm (dental)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('GAUZE-02','Gauze 8x8cm (dental)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('GENTA-01','Gentamycin 5ml/15mg-0,3%',1,7,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('GENTA-02','Gentamycin 80mg/2ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('GRANU-01','granulotec 20g/15ml',1,1,9,NULL,'for permanent obturation after pulpectomy and root- canal treatment, of infected root canals, specifically in presence of a granuloma.',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('GUTTA-01','Gutta percha points',1,NULL,14,NULL,'canal fillers',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HALOP-01','Haloperidol 2mg/ml (20 drops)',1,13,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HEPAR-01','heparin sodium (Hepathromb) 30000ie /100g',1,11,7,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HUMAN-01','Human Immunoglobulin Anti-D (Rh) (Rophylac)-300ug/2ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-01','Hydrobromid Fenoterol (partusisten) 0,5mg/10ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-02','Hydrochlorid Loperamid hci 2mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-03','hydrochlorid Opipramol 50mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-04','Hydrochlorothiazid 160mg/12,5mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-05','Hydrochlorothiazid 25mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-06','Hydrochlorothiazid valsartan 160mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-07','Hydrochlorothiazid valsartan 160mg/25mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-08','Hydrocortison 100mg',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-09','Hydrocortison 10mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-10','Hydrocortison Acetate Crea 1% 15mg (netracort)',1,11,7,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-11','Hydrogen peroxyd 125ml',1,NULL,NULL,NULL,'antiseptic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-12','Hydromorphon hydrochlorid 1.3 mg',1,1,16,NULL,'opioid medication used to treat moderate to severe pain',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYDRO-13','Hydroxyethyl 500ml (Voluven)',1,2,11,NULL,'volume expander in intravenous therapy',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYOSC-01','Hyoscine Butylbromide 10mg (oraspas)',1,1,16,NULL,'antispasmodic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYOSC-02','Hyoscine Butylbromide 20mg/ml',1,2,11,NULL,'antispasmodic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('HYOSC-03','Hyoscine Hydrobromid 300ug',1,1,16,NULL,'anti-cholinergic and is primarily used in the palliative setting to manage noisy breathing at the end of life',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('IBUPR-01','Ibuprofen 100mg/5ml-100ml',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('IBUPR-02','Ibuprofen 100mg+ paracetamol 162,5mg (Ibumol)60ml',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('IBUPR-03','Ibuprofen 125mg (nurofen)',1,5,21,NULL,'painkiller and anti-inflammatory for babies and toddlers aged between 3 months and 2 years',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('IBUPR-04','Ibuprofen 200mg',1,1,16,NULL,'Pain killer and anti inflammatory',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('IBUPR-05','Ibuprofen 400mg',1,1,16,NULL,'Pain killer and anti inflammatory',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('IBUPR-06','Ibuprofen 400mg+paracetamol 325mg (ibumol725mg)',1,1,16,NULL,'Pain killer + anti inflammatory and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ILON -01','ilon classic Ointment 25 g',1,11,7,NULL,'Treatment of mild, localized purulent inflammation of the skin. · Treatment of inflamed hair follicles and sweat glands · Acne treatment',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('INSUL-01','insuline 10ml-100iu/ml (Actrapid',1,2,11,NULL,'Herbal anti-inflamatory',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('IODOF-01','Iodoform 15g',1,11,18,NULL,'dental disinfectant',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('KETAM-01','Ketamine Hydrochloride 25 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('KETAM-02','Ketamine Hydrochloride 50 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('KETOP-01','Ketoprofene 100 mg',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LACTO-01','Lactose monohydrate (tanakan) 40mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LEVET-01','Levetiracetam 500mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LEVOF-01','Levofloxacyne 500mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LEVOF-02','Levofloxacyne 750mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LEVOT-01','Levothyroxyn-Natrium 50mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LIDOC-01','Lidocain 2%-30ml',1,12,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LIDOC-02','Lidocain Hydrochlorid 1%',1,2,11,NULL,'local anesthetic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LIDOC-03','Lidocaine Hydrochloride 1%',1,13,11,NULL,'Local anaesthesia by surface infiltration, regional, epidural and caudal routes, dental anaesthesia, either alone or in combination with adrenaline.',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LIDOC-04','Lidocaine Hydrochloride 2%',1,13,11,NULL,'Local anaesthesia by surface infiltration, regional, epidural and caudal routes, dental anaesthesia, either alone or in combination with adrenaline.',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LIQUI-01','Liquigel 30ml',1,11,7,NULL,'relieves vaginal dryness',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('LOSAR-01','Losartan Potassium + hydrochlortiazid 100/12,5 (colosar)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MACRO-01','Macrogol 13,7g',1,1,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MAGNE-01','Magnesium 150mg (Magne-denk)',1,1,10,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MAGNE-02','Magnesium Sulfate 50%-10ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MATRI-01','Matrix band',2,NULL,14,NULL,'aid in restoring normal contour and contact areas and to prevent extrusion of restorative materials into gingival tissues',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MEBEN-01','Mebendazole 100mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MEBEV-01','Mebeverine hydrochloride (Duspatalin) 135mg',1,1,16,NULL,'Antispasmodic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MEDIG-01','Medigel( lipogel hydroactive) 20g',1,11,7,NULL,'fast wound healing cream',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MEDRO-01','Medroxyprogesterone Acetate 150 mg/ml (depo provera)',1,2,11,NULL,'long-term female contraception',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MEPIV-01','Mepivacain Hydrochlorid 3% (With Adrenalin) 54mg',1,2,11,NULL,'local or regional analgesia and anesthesia by local infiltration',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MEPIV-02','Mepivacain Hydrochlorid 3% (Without Adrenalin) 54mg',1,2,11,NULL,'local or regional analgesia and anesthesia by local infiltration',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MEPTA-01','Meptazinol hydrochlorid (meptid) 100mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MESAL-01','Mesalazin 500mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METAM-01','Metamizola Nitrate (Novamin Sulfate) 1000mg/2ml',1,2,11,NULL,'painkiller,antipyretic with anti-inflammatory effects',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METAM-02','Metamizole Nitrate (Novamin Sulfate) 500mg',1,1,16,NULL,'painkiller, antipyretic with anti-inflammatory effects',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METAM-03','Metamizole Nitrate (Novamin Sulfate) 500mg/ml-100ml',1,1,9,NULL,'painkiller, antipyretic with anti-inflammatory effects',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METFO-01','Metformin hydrochlorid 1000 mg',1,1,16,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METFO-02','Metformin Hydrochlorid 1g',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METHO-01','Methocarbamol-ibuprofen 700mg (Flexdol)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METHY-01','Methyl hydroxybenzoate 2%-20ml (Lignocain HC)',1,2,11,NULL,'preservatives for creams, emulsions, lotions and ophthalmic solutions, and they are used to preserve local anæsthetics.',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METHY-02','Methyldopa 250mg',1,1,16,NULL,'antihypertensive',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METHY-03','Methylprednisolone (Depo-medrol)-40mg/ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METHY-04','Methylprednisolone (Depo-medrol)-80mg/ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METHY-05','Methylprednisolone 120mg/2ml (Solu-Medrol)',1,2,11,NULL,'anti-inflammatory and immunosuppressive',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METHY-06','Methylprednisolone 20mg/2ml (Solu-Medrol)',1,2,11,NULL,'anti-inflammatory and immunosuppressive',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METHY-07','Methylprednisolone 40mg/2ml (Solu-Medrol)',1,2,11,NULL,'anti-inflammatory and immunosuppressive',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METOC-01','Metocarbamol 500mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METOC-02','Metoclopramid 10mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METOC-03','Metoclopramid 10mg/2ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METOP-01','Metopinazin 7,5mg (vogalene)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METOP-02','Metoprolol succinate (Lopressor) 50mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METOP-03','Metoprolol tartrate(Lopressor) 100mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METOP-04','Metoprolol-succinate 47,5mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METOP-05','Metoprolol-succinate retard 50mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METRO-01','Metronidazole 100ml',1,1,4,NULL,'pediatric antibiotic and antiprotozoal',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METRO-02','Metronidazole 250mg',1,1,16,NULL,'antibiotic and antiprotozoal',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METRO-03','Metronidazole 500mg (flagyl)',1,1,12,NULL,'antibiotic and antiprotozoal',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METRO-04','Metronidazole 500mg (flagyl)',1,1,16,NULL,'antibiotic and antiprotozoal',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METRO-05','Metronidazole 500mg/100ml',1,2,11,NULL,'antibiotic and antiprotozoal',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('METYL-01','Metylsulfat neostigmin (prostigmin) 0,5mg/1ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MICON-01','Miconazole 2% 30g',1,11,7,NULL,'antifungal',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MICRO-01','Microlax 5ml',1,5,7,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MIDAZ-01','Midazolam 15 mg/3 ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MIDAZ-02','Midazolam 15mg/3ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MIRTA-01','Mirtazapin 15mg',1,1,16,NULL,'antidepressant',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MIRTA-02','Mirtazapin 30mg',1,1,16,NULL,'antidepressant',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MISOP-01','Misoprostol 200ug',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MIVAC-01','Mivacuriumchlorid 10 mg (mivacron)',1,2,11,NULL,'skeletal muscle relaxant',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MONOB-01','Monobasic sodium phosphate (normacol) 130ml',1,5,7,NULL,'anticonstipation',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MORPH-01','Morphine 10 mg',1,2,11,NULL,'opioid medication used to treat moderate to severe pain',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MORPH-02','Morphine 10mg - 1ml',1,2,11,NULL,'second generation antipsychotic (SGA) or atypical antipsychotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MORPH-03','Morphine Sulfate 10 mg',1,1,16,NULL,'opioid medication used to treat moderate to severe pain',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MULTI-01','Multivitamin 100ml (cirovit)',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MULTI-02','Multivitamin 100ml (pediavit)',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('MULTI-03','Multivitamine 10mg - 900ui',1,1,16,NULL,'A,B,B2,B3 (PP), B5, D3',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NADRO-01','Nadroparine-calcium 0,3ml-2850ie  (fraxiparine)',1,2,11,NULL,'anticoagulants or antithrombotic agents',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NALOX-01','Naloxone 0,4mg/1ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NALOX-02','Naloxone Hydrochlorid 0.4 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NATRI-01','Natrium chlorid 0,9%-10ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NATRI-02','Natrium Selenit 300ug (Cefasel)',1,1,16,NULL,'Nutritional supplements',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NATUR-01','Natural Shade Composite 4g',2,NULL,14,NULL,'reconstructor of both dentin and enamel',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NEEDL-01','Needles 27G (dental)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NEFOP-01','nefopam hydrochlorid (Acupan)',1,2,11,NULL,'non-opioid painkilling medication, that is primarily used to treat moderate to severe pain.',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NEOMY-01','Neomycin Sulfate & Batracin Zinc 15g (Neba-Sporin)',1,11,7,NULL,'antibiotic',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NEOST-01','Neostigmine Methylsulfate 0.5 mg/ml',1,2,11,NULL,'anticholinesterase: treatment of Myasthenia Gravis',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NICAR-01','Nicardipin chlorhydrate (loxen) 20mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NICAR-02','Nicardipin chlorhydrate (loxen) 50mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NICAR-03','Nicardipine 10 mg/10 ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NIFED-01','Nifedipine 10mg',1,1,16,NULL,'channel blocker medication',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NIFED-02','Nifedipine 20mg',1,1,16,NULL,'channel blocker medication',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NIFED-03','Nifedipine-retard 20mg',1,1,16,NULL,'channel blocker medication',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NITRO-01','Nitrofurantoin 50mg',1,1,16,NULL,'antibiotic, used to treat bladder infections',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NITRO-02','Nitroligual 0,4mg-20,9ml',1,11,19,NULL,'nitrates: relieve chest pain (angina) in people that have a certain heart condition (coronary artery disease)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NYSTA-01','Nystatin 100,000units',1,6,12,NULL,'antifungal: used to treat candidiasis',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NYSTA-02','Nystatin/candistatin gel 30g',1,11,7,NULL,'antifungal',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('OCTAN-01','Octanisept 20ml',1,11,7,NULL,'short-term antiseptic treatment of mucous membranes, adjacent skin',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('OFLOX-01','Ofloxacyn 1,5mg/0,5ml (oflocet)',1,11,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('OLANZ-01','Olanzapine 5mg',1,1,16,NULL,'second generation antipsychotic (SGA) or atypical antipsychotic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('OMEPR-01','Omeprazole 20mg',1,1,10,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('OMEPR-02','Omeprazole 40mg',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('OPTIB-01','Optibond 8ml',1,11,18,NULL,'bonding agent',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ORAL -01','Oral Rehydration Salt Powder 20,5g',1,1,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('OTRIV-01','Otriven 0.1%',1,8,9,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-01','Paracetamol + codeine 125mg',1,5,21,NULL,'Higher Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-02','Paracetamol + codeine 500/30mg',1,1,16,NULL,'Higher Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-03','Paracetamol 1000mg (Doliprane)',1,5,21,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-04','Paracetamol 100mg (Doliprane)',1,5,21,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-05','Paracetamol 10mg/ml-1g/100ml',1,2,11,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-06','Paracetamol 125mg (acetaminophen)',1,5,21,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-07','Paracetamol 125mg/5ml',1,1,4,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-08','Paracetamol 125mg-100ml',1,1,4,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-09','Paracetamol 1g',1,1,16,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-10','Paracetamol 200mg (Doliprane)',1,5,21,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-11','Paracetamol 200mg (Doliprane)',1,1,9,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-12','Paracetamol 300mg (Doliprane)',1,5,21,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-13','Paracetamol 500mg',1,1,16,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-14','Paracetamol 500mg',1,5,21,NULL,'Analgesics and antipyretic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-15','Paracetamol 60ml (pediatric )',1,1,4,NULL,'Antipyrec and analgesic',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PARAC-16','Paracetamol -propyphenazone-caffeine 430mg (trimol)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PC 30-01','PC 30 V',1,11,7,NULL,'Skin Care for Pressure Ulcer Prevention',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PENAT-01','Penaten 15ml',1,11,7,NULL,'provides effective treatment to help soothe irritation caused by diaper rashes',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PENIC-01','Penicillin 1Miu/ui(0,6g)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PENIC-02','Penicillin 2.4000.000ui',1,12,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PENIC-03','Penicillin phenoxymethyl 1,200,000',1,1,16,NULL,'antibiotic used to treat bacterial infections, including ear, chest, throat and skin infections',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PENTH-01','Penthenol 100g',1,11,7,NULL,'moisturizer',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHENO-01','Phenobarbital 50 mg',1,1,16,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHENO-02','Phenobarbital Sodium 40 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHENO-03','Phenobarbital Sodium 50mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHENY-01','Phenylephrine HCI 1,0%',1,8,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHLOR-01','Phloroglucinol 150mg (spasfon)',1,5,21,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHLOR-02','Phloroglucinol 40mg (spasfon)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHLOR-03','Phloroglucinol 80mg (spasfon)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHYSI-01','Physiologic serum (physidose) 5ml',1,13,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHYTO-01','Phytomenadion (Vitamin K1) 10mg/ml',1,12,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHYTO-02','Phytomenadion (Vitamin K1) 10mg/ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHYTO-03','Phytomenadion (Vitamin K1) 10mg/ml',1,13,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PHYTO-04','Phytomenadion (Vitamin K1) 10ml',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PIPAM-01','Pipamperon hydrochlorid (Didiperone) 200ml',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('POLIS-01','Polishing stem disc',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('POSIF-01','Posiformin® 2%',1,11,7,NULL,'antiseptic and anti-secretory eye cream',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('POTAS-01','Potassium Chlorid 600mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('POTAS-02','Potassium Chloride 0.1 g/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('POTAS-03','Potassium Chloride 0.2 g/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('POVID-01','Povidone iodee (Betadin) 30g',1,11,7,NULL,'Antiseptic Cream',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PRAZI-01','Praziquantel 600mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PREDN-01','Prednisolon 125mg',1,1,16,NULL,'corticosteroid',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PREDN-02','Prednisolon 20mg',1,1,16,NULL,'corticosteroid',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PREDN-03','Prednisolon 250mg',1,1,16,NULL,'corticosteroid',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PREDN-04','Prednisolon 500mg',1,1,16,NULL,'corticosteroid',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PREDN-05','Prednisolon 50mg',1,1,16,NULL,'corticosteroid',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PREDN-06','Prednisolon 5mg',1,1,16,NULL,'corticosteroid',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('NURSI-01','Nursie 1er Age',1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PRENU-01','Prenursie 400mg',1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PRILO-01','Prilocain hydrochlorid (Xylonest)',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PRILO-02','Prilocain Hydrochlorid 1%-10ml (xylonest)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PROGE-01','Progesterone - Utrogestan 100mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PRONT-01','Prontosan 30ml',1,11,7,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PRONT-02','Prontosan 50g',1,11,7,NULL,'gel for acute, chronic and burn wounds',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PROPO-01','Propofol 1%',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PROPO-02','Propofol 20 mg/ml-50ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PROPR-01','Propranolol 40mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PROPR-02','Propranolol 50g',1,1,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PULPO-01','Pulpotec 15g',1,1,9,NULL,'non-resorbable filling paste used for rapid and long- term treatment of pulpitis',10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PYLOO-01','Pyloocain 30g',1,11,7,NULL,'treatment of hemorrhoids and anal fissures for topical use',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('PYRID-01','Pyridoxine 50mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('QUINI-01','Quinine Sulfate 300mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('RACEC-01','Racecadotril 10mg (tiorfan)',1,1,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('RACEC-02','Racecadotril 175mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('RANIT-01','Ranitidine 50 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('REMIF-01','Remifentanyl 1mg',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('REMIF-02','Remifentanyl 5mg',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('REPAG-01','Repaglinide (novonorm) 0,5mg',1,1,16,NULL,'antidiabetic medicine',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ROOT -01','Root canal',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ROSUV-01','Rosuvastatin 5mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SACCH-01','Saccharomycetes (Perenterol) 250mg',1,1,10,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SACCH-02','Sacchromyces boulardii 250mg (ultra-levure)',1,1,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SALBU-01','Salbutamol 0,5mg-1ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SALBU-02','Salbutamol 100ug',1,9,20,NULL,'asthma reliever and anti-chronic obstructive pulmonary disease (COPD)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SALBU-03','Salbutamol sulfate 1,25mg/2,5ml',1,9,20,NULL,'asthma reliever and anti-chronic obstructive pulmonary disease (COPD)',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SALIV-01','Saliva ejector',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SCROF-01','Scrofalon Sterile Absorbable Gelatin Sponge (dental)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERTA-01','Sertaconazole Nitrate',1,11,19,NULL,'antimycotic especially feet mushrooms',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-01','Serum (Sodium (0,9%)+glucose (5%))',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-02','Serum Glucose 20%-10ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-03','Serum Glucose 40%-10ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-04','Serum Glucose hypertonique 10% 500ml (SGH)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-05','Serum Glucose Isotonique 5% 100ml (SGI)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-06','Serum Glucose Isotonique 5% 500ml (SGI)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-07','Serum Ringer lactate 500ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-08','Serum Sodium chlorure 0,9% 100ml (SSI)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-09','Serum Sodium chlorure 0,9% 10ml (SSI)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-10','Serum Sodium chlorure 0,9% 500ml (SSI)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-11','Serum Sodium chlorure 0,9% 50ml (SSI)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SERUM-12','Serum Sodium chlorure 0,9% 60ml (SSI)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SEVOF-01','Sevoflorane (750ml)',1,9,20,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SILVE-01','Silver sulfadiazine 1% 20g (Silvadene)',1,11,7,NULL,'topical antibiotic used in partial thickness and full thickness burns to prevent infection',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SIMET-01','Simeticon 30 ml',1,1,9,NULL,'Anti-Gas Generic',8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SODIU-01','Sodium 1000 mg',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SODIU-02','Sodium 250 mg',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SODIU-03','Sodium bicarbonate 50ml -84mg/ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SODIU-04','Sodium chlorid 0.9%',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SODIU-05','Sodium Chloride 0.1 g/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SODIU-06','Sodium Picosulphate 7,5mg/ml (15drops)',1,1,9,NULL,'citric acid solution used to clean out the intestines before surgery or certain procedures',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SOVEN-01','SOVENTOL Hydrocort 0,5% Creme 15 g',1,11,7,NULL,'Hydrocortison',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SPINA-01','Spinal Needle',2,NULL,14,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SPIRO-01','Spironolacton 25mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SPIRO-02','Spironolacton 50mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('STRAT-01','Stratacel 10g',1,11,7,NULL,'cream to cover a wound',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('STRAT-02','Stratamed  10g',1,11,7,NULL,'wound dressing that can speed up the healing process after cosmetic procedures or treatments',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('STRIP-01','Strips (dental)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SULTA-01','Sultanmicillin Dihydrat 375mg (unacid)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('SUTUR-01','Suture 9,0/15cm (dental)',2,NULL,14,NULL,NULL,10);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TEA (-01','Tea (Taf)',1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TERBI-01','Terbinafin 250mg',1,1,16,NULL,'antifungal',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TERBI-02','Terbinafin hydrochlorid 15g',1,11,7,NULL,'antifungal',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TETRA-01','Tetracyclin Gel 1%',1,11,7,NULL,'antibiotic',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TETRA-02','Tetracyclin Gel 3%',1,11,7,NULL,'antibiotic',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('THIOP-01','Thiopental 1000mg',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TILID-01','Tilidin retard 100mg/8mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TILID-02','Tilidin retard 50mg/4mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TOBRA-01','Tobramycin 100ml-0,3%',1,7,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TOBRA-02','Tobramycin-dexamethason 5ml',1,7,9,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TOKO -01','Toko oil 300ml',1,11,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TOLON-01','Tolonium chlorid 300mg/ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TOLON-02','Tolonium chlorid 30mg/ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TORAS-01','Torasemid 10mg',1,1,16,NULL,'diuretic medication',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TORAS-02','Torasemid 5mg',1,1,16,NULL,'diuretic medication',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TRAMA-01','Tramadol 100mg/2ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TRAMA-02','Tramadol 50 mg/ml',1,2,11,NULL,NULL,8);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TRAMA-03','Tramadol Hydrochlorid 100mg',1,5,21,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TRAMA-04','Tramadol Hydrochlorid 100mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TRANE-01','Tranexamic acid 100mg/ml (exacyl)',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TRANE-02','Tranexamic acid 1g/10ml (exacyl)',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TRANE-03','Tranexamic acid 500mg (cyklokapron)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('TRIME-01','Trimetazidin hydrochlorid 35mg (TrivedonLM)',1,1,16,NULL,'fatty acid oxidation inhibitors: used to prevent and treat the symptoms of angina (chest pain).',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('URSOF-01','Ursofalk 250mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('URSOF-02','Ursofalk 500mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('VENLA-01','Venlafaxin - retard 75mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('VERAP-01','Verapamil hydrochlorid - retard 240mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('VITA--01','Vita-Horm Baby Skin Cream 30 g',1,11,7,NULL,'moisturizer',9);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('VITAM-01','Vitamin B complex 500mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('VITAM-02','Vitamin C 250mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('VITAM-03','Vitamin C 500mg',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('VITAM-04','Vitamin C 500mg/5ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('VITAM-05','Vitamin D 500mg (Zymafluor D)',1,1,16,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('VITAM-06','Vitamin mineral 100ml (bombom)',1,1,4,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('XIPAM-01','Xipamid 10mg',1,1,16,NULL,'diuretic, used for the treatment of oedema and hypertension',NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('XYLOC-01','Xylocain 2% -5ml',1,2,11,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('XYLOC-02','Xylocain 50ml (Alcool 96%)',1,11,19,NULL,NULL,NULL);
INSERT INTO items(code,description,item_type_id,administration_id,item_unit_id,price,purpose_of_use,location_id) VALUES ('ZINC -01','zinc oxide 500mg',1,1,15,NULL,'temporary filling and sealing materials',10);
