INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (1,NULL,NULL,'ULM',0,1);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (2,NULL,NULL,'MidMob',0,2);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (3,NULL,NULL,'DentMob',0,3);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (4,NULL,NULL,'Ambulance car',0,4);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (5,NULL,NULL,'Outreaches with partners',0,5);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (6,NULL,NULL,'Consultation',1,6);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (7,NULL,NULL,'Other vaccination',1,6);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (8,NULL,NULL,'Injury/Wound care',1,6);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (9,NULL,NULL,'Consultation',1,7);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (10,NULL,NULL,'Treatment',1,7);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (11,NULL,NULL,'ultrasound',1,8);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (12,NULL,NULL,'First cpn',0,8);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (13,NULL,NULL,'Cpn followup',1,8);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (14,NULL,NULL,'Post partum baby',1,8);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (15,NULL,NULL,'Post partum mom',1,8);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (16,NULL,NULL,'Post partum meeting',1,8);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (17,NULL,NULL,'Vaccination',1,9);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (18,NULL,NULL,'routine checkup',1,9);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (19,NULL,NULL,'Sickness',1,9);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (20,NULL,NULL,'Injury/Wound care',1,9);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (21,NULL,NULL,'Dermatology',1,10);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (22,NULL,NULL,'Other',1,11);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (23,NULL,NULL,'Generalist',1,12);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (24,NULL,NULL,'Dental',1,13);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (25,NULL,NULL,'Obstetrics',1,14);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (26,NULL,NULL,'Pediatrics',1,15);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (27,NULL,NULL,'Dermatology',1,16);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (28,NULL,NULL,'Other',1,17);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (29,NULL,NULL,'Obstetrics',1,18);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (30,NULL,NULL,'Generalist',1,19);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (31,NULL,NULL,'Dental',1,20);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (32,NULL,NULL,'Obstetrics',1,21);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (33,NULL,NULL,'Pediatrics',1,22);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (34,NULL,NULL,'Dermatology',1,23);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (35,NULL,NULL,'Other',1,24);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (36,NULL,NULL,'Generalist',1,25);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (37,NULL,NULL,'Dental',1,26);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (38,NULL,NULL,'Obstetrics',1,27);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (39,NULL,NULL,'Pediatrics',1,28);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (40,NULL,NULL,'Dermatology',1,29);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (41,NULL,NULL,'Other',1,30);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (42,NULL,NULL,'Hospital in general',1,31);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (43,NULL,NULL,'Dermatology',1,32);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (44,NULL,NULL,'Ophthalmology',1,33);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (45,NULL,NULL,'German doctors',1,34);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (46,NULL,NULL,'O-therapy',1,35);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (47,NULL,NULL,'Other',1,36);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (48,NULL,NULL,'Generalist',1,37);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (49,NULL,NULL,'Dental',1,38);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (50,NULL,NULL,'Obstetrics',1,39);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (51,NULL,NULL,'Pediatrics',1,40);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (52,NULL,NULL,'Dermatology',1,41);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (53,NULL,NULL,'Other',1,42);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (54,NULL,NULL,'Medical support',0,43);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (55,NULL,NULL,'Families',0,44);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (56,NULL,NULL,'MHM Staff Families',0,45);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (57,NULL,NULL,'Kids',0,46);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (58,NULL,NULL,'MHM Staff Kids',0,47);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (59,NULL,NULL,'Milk Program',1,48);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (60,NULL,NULL,'Pregnancies',1,49);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (61,NULL,NULL,'Chaplaincy',1,50);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (62,NULL,NULL,'Kids club',1,51);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (63,NULL,NULL,'Play mobile',1,52);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (64,NULL,NULL,'Prayer worship Alpha course',1,53);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (65,NULL,NULL,'Sensibilization',1,54);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (66,NULL,NULL,'Admin',1,55);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (67,NULL,NULL,'Medical',1,56);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (68,NULL,NULL,'Social',1,57);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (69,NULL,NULL,'Technical',1,58);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (70,NULL,NULL,'Admin',1,59);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (71,NULL,NULL,'Medical',1,60);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (72,NULL,NULL,'Social',1,61);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (73,NULL,NULL,'Technical',1,62);
INSERT INTO service_activities(id,created_at,updated_at,name,joyCenter,service_id) VALUES (16,NULL,NULL,'Family planning',1,8);
